name: Release

on:
  push:
    branches:
      - main
      - development

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Verify token presence
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: echo "GH_TOKEN is ${GH_TOKEN:+set ✅}"

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: pnpm semantic-release
